#!/usr/bin/env bash
#
# Collect container vulnerabilities for a set of images with grype and render a
# Markdown report. This is intentionally NON-GATING: it always exits 0 (unless
# misused) so it can be wired into release CI as an informational artifact that
# is posted to the release PR rather than a pass/fail gate.
#
# Usage:
#   scripts/vuln-report.sh OUTPUT.md IMAGE [IMAGE ...]
#
# Environment:
#   VULN_REPORT_VERSION  Optional release label shown in the report header.
#
# Requires: grype, python3. Images must be pullable (run `docker login` first
# for private registries).
set -uo pipefail

OUT="${1:-}"
if [ -z "$OUT" ]; then
  echo "usage: $0 OUTPUT.md IMAGE [IMAGE ...]" >&2
  exit 2
fi
shift
if [ "$#" -eq 0 ]; then
  echo "$0: no images supplied" >&2
  exit 2
fi
if ! command -v grype >/dev/null 2>&1; then
  echo "$0: grype is not installed" >&2
  exit 2
fi

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT
manifest="$workdir/manifest.tsv"
: > "$manifest"

i=0
for ref in "$@"; do
  i=$((i + 1))
  json="$workdir/scan-$i.json"
  status="ok"
  echo "Scanning $ref ..." >&2
  if ! grype "$ref" -o json -q > "$json" 2> "$workdir/err-$i.log"; then
    status="error"
    echo "  grype failed for $ref (see log); recording as not-scanned" >&2
  fi
  printf '%s\t%s\t%s\n' "$ref" "$json" "$status" >> "$manifest"
done

GRYPE_VERSION="$(grype version 2>/dev/null | awk -F': *' '/^Version:/{print $2}')"
export GRYPE_VERSION
export REPORT_VERSION="${VULN_REPORT_VERSION:-}"
export REPORT_MANIFEST="$manifest"

python3 - "$OUT" <<'PY'
import collections, datetime, json, os, sys

out_path = sys.argv[1]
manifest = os.environ["REPORT_MANIFEST"]
grype_ver = os.environ.get("GRYPE_VERSION", "") or "unknown"
release = os.environ.get("REPORT_VERSION", "")

SEV = ["Critical", "High", "Medium", "Low", "Negligible", "Unknown"]
ABBR = {"Critical": "C", "High": "H", "Medium": "M", "Low": "L",
        "Negligible": "N", "Unknown": "?"}

rows = []          # (ref, Counter or None, fixable_int)
fixable = []       # (tag, pkg, version, severity, cve, fixed_in)
totals = collections.Counter()
total_fixable = 0
unique_cves = set()
scanned = 0
errors = 0

with open(manifest) as fh:
    entries = [ln.rstrip("\n").split("\t") for ln in fh if ln.strip()]

# Sort for stable, readable output.
entries.sort(key=lambda e: e[0])

for ref, jpath, status in entries:
    if status != "ok" or not os.path.exists(jpath) or os.path.getsize(jpath) == 0:
        rows.append((ref, None, 0))
        errors += 1
        continue
    try:
        data = json.load(open(jpath))
    except Exception:
        rows.append((ref, None, 0))
        errors += 1
        continue
    scanned += 1
    counts = collections.Counter()
    fx = 0
    tag = ref.rsplit(":", 1)[-1]
    for m in data.get("matches", []):
        v = m["vulnerability"]
        a = m["artifact"]
        sev = v.get("severity") or "Unknown"
        if sev not in SEV:
            sev = "Unknown"
        counts[sev] += 1
        totals[sev] += 1
        unique_cves.add(v.get("id", "?"))
        is_fixed = (v.get("fix", {}) or {}).get("state") == "fixed"
        if is_fixed:
            fx += 1
            total_fixable += 1
            if sev in ("Critical", "High"):
                fixed_in = ",".join((v.get("fix", {}) or {}).get("versions", [])) or "-"
                fixable.append((tag, a.get("name", "?"), a.get("version", "?"),
                                sev, v.get("id", "?"), fixed_in))
    rows.append((ref, counts, fx))

now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
total_matches = sum(totals.values())

lines = []
hdr = "## Container vulnerability report"
if release:
    hdr += f" — `{release}`"
lines.append(hdr)
lines.append("")
lines.append(
    f"Generated by grype `{grype_ver}` on {now}. "
    f"**Informational only — this report does not gate the release.**"
)
lines.append("")
lines.append(
    f"**{scanned} image(s) scanned** "
    + (f"({errors} not published / not scanned) " if errors else "")
    + f"· **{total_matches} matches** · **{len(unique_cves)} unique CVEs** "
    f"· **{total_fixable} fixable**"
)
lines.append("")
sev_summary = " · ".join(f"{s} {totals.get(s, 0)}" for s in SEV)
lines.append(f"Severity totals: {sev_summary}")
lines.append("")

# Per-image table.
header = "| Image | " + " | ".join(ABBR[s] for s in SEV) + " | Fixable |"
sep = "|---|" + "".join("--:|" for _ in SEV) + "--:|"
lines.append(header)
lines.append(sep)
for ref, counts, fx in rows:
    tag = ref.rsplit(":", 1)[-1]
    if counts is None:
        lines.append(f"| `{tag}` | " + " | ".join("–" for _ in SEV) + " | – |  _(not scanned)_")
        continue
    cells = " | ".join(str(counts.get(s, 0)) for s in SEV)
    lines.append(f"| `{tag}` | {cells} | {fx} |")
lines.append("")
lines.append(
    "Legend: **C**ritical · **H**igh · **M**edium · **L**ow · "
    "**N**egligible · **?** Unknown."
)
lines.append("")

# Fixable Critical/High detail.
lines.append("<details>")
if fixable:
    lines.append(f"<summary>Fixable Critical/High vulnerabilities ({len(fixable)})</summary>")
    lines.append("")
    lines.append("| Image tag | Package | Installed | Severity | Vulnerability | Fixed in |")
    lines.append("|---|---|---|---|---|---|")
    fixable.sort(key=lambda r: (SEV.index(r[3]), r[0], r[1]))
    for tag, pkg, ver, sev, cve, fixed_in in fixable:
        lines.append(f"| `{tag}` | {pkg} | {ver} | {sev} | {cve} | {fixed_in} |")
else:
    lines.append("<summary>Fixable Critical/High vulnerabilities (0)</summary>")
    lines.append("")
    lines.append("No fixable Critical/High vulnerabilities found "
                 "(remaining findings are either lower severity or have no vendor fix available).")
lines.append("</details>")
lines.append("")

with open(out_path, "w") as fh:
    fh.write("\n".join(lines) + "\n")

print(f"Wrote {out_path}: {scanned} scanned, {total_matches} matches, "
      f"{total_fixable} fixable, {errors} not scanned.")
PY
